project:
  type: website
  output-dir: docs

website:
  title: "Plot thoughts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Workshops

format:
  html:
    theme: 
      - lux
      - customstyles.scss
    mainfont: Nanum Myeongjo
    css: styles.css
    toc: true



