project:
  type: website
  output-dir: docs

website:
  title: "Figs"
  favicon: images/fig.png
  navbar:
    left:
      - href: posts.qmd
        text: Workshops
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: 
      - lux
      - customstyles.scss
    mainfont: Nanum Myeongjo
    css: styles.css
    toc: true



