project:
  type: website
  output-dir: docs

website:
  title: "figs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      - minty
      - customstyles.scss
    mainfont: Nanum Myeongjo
    css: styles.css
    toc: true



